#!/bin/sh

if [ `hostname` = "wanderlust.local" ]; then
  RUNGHC="/usr/bin/runghc"
elif [ `hostname -d` = "ilab.cs.brown.edu" ] || 
   [ `hostname -d` = "cs.brown.edu" ]; then
  RUNGHC="/pro/plt/ghc/latest/bin/runghc"
else
  echo "Do not know how to build on this host."
  exit 1
fi

PREFIX=`pwd`/dist/install

$RUNGHC Setup.lhs configure --user --prefix=$PREFIX
$RUNGHC Setup.lhs build
