#!/bin/sh

if [ `hostname -d` = "ilab.cs.brown.edu" ] || 
   [ `hostname -d` = "cs.brown.edu" ]; then
  GHCI="/pro/plt/ghc/latest/bin/ghci"
else
  echo "Do not know how to run on this host."
  exit 1
fi

$GHCI -ignore-dot-ghci -fglasgow-exts -isrc

