var sessionId :: string?;

function saveSessionId() :: (->) {
  //match string used to be 'session\=\"(.*\"'
  var match = document.cookie.match('session=\"(.*)\"');
  if (typeof match != "undefined") { //(match) {
    sessionId = match[1]; }
}

function isLoggedIn() :: (-> bool) {
  //if (sessionId) { return true; }
  if (typeof sessionId != "undefined") { return true; }
  else {
    var match = document.cookie.match('session=\"(.*)\"');
    //sessionId = match && match[1];
    if (typeof match != "undefined"){  //(match) {
      sessionId = match[1];
    }
    else
      sessionId = undefined;
    return !!sessionId;
  }
}

/*var Date_shortMonths = ["Jan","Feb","Mar","Apr","May","Jun","Jul",
  "Aug","Sep","Oct","Nov","Dec"];*/

var Date_shortMonths :: Array<string> = ["Jan","Feb","Mar","Apr","May",
  "Jun","Jul", "Aug","Sep","Oct","Nov","Dec"];

//TODO: fix op precedence (== lower than &&)
//TODO: make if(x) work when x is not a bool.
var Date_prototype_formatRelative = function(thisd) :: (Date -> string) {
  //var now = new Date();
  var now :: Date?; //hack to not require a constructor for Date
  if (typeof now == "undefined") return "";

  if ((thisd.getDay() == now.getDay())&&(thisd.getMonth() == now.getMonth()) &&
      (thisd.getFullYear() == now.getFullYear())) {
    return (thisd.getHours() + (thisd.getMinutes() <= 9 ? ":0" : ":") +
            thisd.getMinutes());
  }
  else if (thisd.getFullYear() == now.getFullYear()) {
    return (thisd.getDate() + " " + Date_shortMonths[thisd.getMonth()]);
  }
  else {
    return (thisd.getDate() + " " + Date_shortMonths[thisd.getMonth()] + " "
            + (thisd.getFullYear() % 100));
  }
};
/*
var LINK = function(elt) {
  return A({className: "links", href: 'javascript:undefined'},elt);
};

var isSuccess = function(v) { return v.success; };

function server_e(url,valueE) {
  var response_e = receiver_e();

  var onSuccess = function(transport) {
    saveSessionId();
    response_e.sendEvent(transport.responseText.evalJSON(false));
  };

  var onFailure = function(transport) {
    if (console && console.log) { console.log(transport); }
    var txt = (transport.responseText.length > 0)
              ? transport.responseText : "Session Expired";
    modal(DIV({ className: 'shutdown'},
           txt,
            DIV(A({ style: { fontSize: '12px',color: '#ffffff' },
                    href: 'javascript:window.location.reload()'},
                'Log In Again'))),
      one_e(true),200);
  };

  valueE.lift_e(function(val) {
    if (sessionId) { val.session = sessionId; }
    new Ajax.Request(url,
      { method: 'post'
      , parameters: val
      , onSuccess: onSuccess
      , onFailure: onFailure
      });
  });

  return response_e;
};

// buttonBar :: buttons * buttons * button
// -> { elem: element, clickE: EventStream buttons }
// button = String
// buttons = Array button
//
// You must ensure that the button names are unique, or all hell will
// break loose.
function buttonBar(buttons,rightButtons,initial) {

  rightButtons = rightButtons || [ ];
  var last = false;

  var clickEs = [ ];
  var targetEs = [ ];

  var left = [ ];
  var right = [ ];

  left.push({className: 'buttonBar'});

  buttons.each(function(button) {
    var elem = DIV({className: 'button'},button.toString());
    var e = clicks_e(elem);
    targetEs.push(e);
    clickEs.push(e.constant_e(button));
    left.push(elem);
    if (button == initial) {
      last = elem;
       elem.setStyle({ backgroundColor: '#ffff99', color: '#000000' });
    }
  });

  right.push({className: 'right'});


  rightButtons.each(function(button) {
    var elem = DIV({className: 'button'},button);
    var e = clicks_e(elem);
    targetEs.push(e);
    clickEs.push(e.constant_e(button));
    right.push(elem);
    if (button == initial) {
      last = elem;
       elem.setStyle({ backgroundColor: '#ffff99', color: '#000000' });
    }
  });

  left.push(DIV.apply(this,right));

  var clickE = merge_e.apply(this,clickEs);
  var targetE = merge_e.apply(this,targetEs);

  targetE.lift_e(function(target) {
    if (last) { last.setStyle({ backgroundColor: '', color: '' }); }
    last = target;
    last.setStyle({ backgroundColor: '#ffff99', color: '#000000' });
  });

  return { clickE: clickE
         , elem: DIV.apply(this,left) };
};

// panelB :: EventStream String * { String : Elem or (-> Elem) } * Elem
// -> Behaviour Elem
// Consumes an eventstream carrying panel names, a dictionary that maps
// panel names to either a panel element or a thunk that returns the panel
// element and finally, the initial panel. Returns a behavior carrying the
// current panel
//
// Use a thunk in the dictionary to perform any setup when a panel is swapped
// into the view, even if the layout is static. It's amazing!
function panelB(panelE,panelDict,initialPanel) {
  if (!(initialPanel instanceof HTMLElement)) {
    return "error calling panelB: intialPanel is not an HTML element";
  }

  return panelE.lift_e(function(name) {
    var val = panelDict[name];
    if (typeof(val) == "function") { return val(); }
    else if (val instanceof HTMLElement) { return val; }
    else { return false; // panelE violated the contract, fail silently
    }
  }).filter_e(function(val) { return val instanceof HTMLElement; })
  .startsWith(initialPanel);
};


function modal(content,hideShowE,zIndex) {
  var whiteout = DIV({ style: { position: 'absolute',
                                height: '100%',
                                width: '100%',
                                left: '0px',
                                top: '0px',
                                zIndex: 100,
                                backgroundColor: 'black' }});
  whiteout.setOpacity(0.3);
  document.body.appendChild(whiteout);

  var win = DIV( { style: { position: 'absolute'
                          , left: '25%'
                          , minWidth: '400px'
                          , top: '10%'
                          , zIndex: zIndex || 101
                          } }
               , content);

  document.body.appendChild(win);
  var hidden = false;

  hideShowE.lift_e(function(val) {
    if (!val && !hidden) {
      document.body.removeChild(whiteout);
      document.body.removeChild(win);
      hidden = true;
    }
  });

  return hideShowE;
};*/